* Manual test scripts
** synthetic initial+transitions should cause <scxml> elements to properly update their attributes in linked xml buffers
1. Create new blank document.
2. By mouse only add one <state> to the scxml, edit the <state> to have a valid id.
3. By mouse only add an initial= to the scxml.
4. By mouse only add a transition to the initial=
5. By mouse only connect the end of that transition to the <state>
Confirm - in the xml the <scxml> has a proper initial= attribute.

** synthetic initial+transitions should refuse a mouse connect when the target state does not have an id set
1. Create new blank document.
2. By mouse only add one <state> to the scxml, ensure the <state> has _no_ valid id!
3. By mouse only add an initial= to the scxml.
4. By mouse only add a transition to the initial=
5. By mouse only connect the end of that transition to the <state>
Confirm - No error, but a message should be displayed describing that you can't auto-connect without an id set on the <state>.

** synthetic initial+transitions should cause <state> elements to properly update their attributes in linked xml buffers
1. Create new blank document.
2. By mouse only add one <state> to the scxml, edit the <state> to have a valid id.
3. By mouse only add one child <state> into the <state> you just created, edit the child <state> to have a valid id.
4. By mouse only add an initial= to the parent <state>.
5. By mouse only add a transition to the initial=
6. By mouse only connect the end of that transition to the child <state>
Confirm - in the xml the parent <state> has a proper initial= attribute.

** adding a transition by mouse should leave the transition's end point at the mouse's location
1. Create new blank document.
2. By mouse only add one <state> to the scxml
3. By mouse only add a transition to the <state>
Confirm - When clicking the mouse to add the transition the end point of the transition will be in the same place as the mouse cursor

** deleting the target state of a transition does not fully remove the target state
 - not working :(
1. Create a new blank document.
2. By mouse only add two sibling states in the main <scxml> element and assign them both valid ids.
3. By mouse only create transition from one state to the other.
4. Select the state targeted by transition and delete it.
Confirm - the state delete is entirely gone and the transition doesn't retain a reference to it by displaying the target end of the transition's drawing as being connected.
Confirm - the transition still retains the value of the target= attribute.

** deleting a state with transitions to another fails to remove child transitions
1. Create a new blank document.
2. By mouse only add two sibling states in the main <scxml> element and assign them both valid ids.
3. By mouse only create a transition from the first <state> to the second.
5. By mouse, select the first <state> element and delete it.
Confirm - the first state is deleted and its child <transition> element is also deleted.

** doing things by keyboard (adding a transition isn't working)
